# Generated by Django 3.1.4 on 2021-01-09 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0002_category_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expenses',
            name='date_added',
            field=models.DateTimeField(),
        ),
    ]
