# Generated by Django 3.1.4 on 2021-01-14 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('incomes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='incomes',
            options={'ordering': ['-date_added'], 'verbose_name': 'Income', 'verbose_name_plural': 'Incomes'},
        ),
    ]
